require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - db/schema.rb
    - js/*
    - notes/*
    - js/*
    - lib/grpc/*

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Exclude:
    - 'spec/services/blockchain_data_fetcher/client/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/Rails/InferredSpecType:
  Enabled: false

Style/Documentation:
  Enabled: false
