require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - db/schema.rb
    - notes/*

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/Rails/InferredSpecType:
  Enabled: false

Style/Documentation:
  Enabled: false
