version: '3.8'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: position_watcher_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  ruby_app:
    platform: linux/amd64
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=position_watcher_dev
      - DATABASE_URL=postgres://postgres:postgres@db:5432/position_watcher_dev
      - NODE_APP_HOST=node_app
      - REDIS_URL=redis://redis:6379

  node_app:
    build:
      context: ./js/blockchainDataFetcher
      dockerfile: Dockerfile.node
    volumes:
      - ./js/blockchainDataFetcher:/app/js/blockchainDataFetcher
    ports:
      - "50051:50051"

volumes:
  db_data:
