# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: blockchain_data_fetcher.proto for package ''

require 'grpc'
require_relative './blockchain_data_fetcher_pb'

module BlockchainDataFetcher
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'BlockchainDataFetcher'

    rpc :GetTokenData, ::TokenRequest, ::TokenResponse
    rpc :GetPositionData, ::PositionRequest, ::PositionResponse
    rpc :GetPoolState, ::PoolStateRequest, ::PoolStateResponse
  end

  Stub = Service.rpc_stub_class
end
