name: Ruby CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up database
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/position_watcher_test
          RACK_ENV: test
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0

      - name: Run RSpec
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/position_watcher_test
          RACK_ENV: test
        run: bundle exec rspec

      - name: Run bundle-audit
        run: bundle exec bundle-audit check --update

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Check database consistency
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/position_watcher_test
          RACK_ENV: test
        run: bundle exec ruby database_consistency_runner.rb
